# Generated by Django 4.1.7 on 2023-04-12 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=255)),
                ('answer1', models.CharField(max_length=30)),
                ('answer2', models.CharField(max_length=30)),
                ('answer3', models.CharField(max_length=30)),
                ('answer4', models.CharField(max_length=30)),
                ('type_answer', models.CharField(choices=[('radio', 'Radio'), ('True/False', 'True False'), ('Вопрос с открытым ответом', 'Open Answer')], default='radio', max_length=30)),
                ('right_answer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_create', models.DateField(auto_now=True)),
                ('views', models.IntegerField()),
                ('rating', models.FloatField()),
                ('icon', models.ImageField(upload_to='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QIQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='default.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='default.quiz')),
            ],
        ),
    ]
