# Generated by Django 4.1.7 on 2023-04-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='rating',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
