# Generated by Django 4.1.7 on 2023-04-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0006_remove_quiz_rating_alter_question_answer2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='count_of_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
