# Generated by Django 4.1.7 on 2023-04-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0007_quiz_count_of_rating_quiz_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='icon',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
